config/routes.rb
Rails.application.routes.draw do
    root               'application#index'
    get    'index'   => 'application#index'
    get    'about'   => 'application#about'
    get    'contact' => 'application#contact'
	get    'signup'  => 'users#new'
	get    'login'   => 'sessions#new'
	post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'
    get    'reservations' => 'reservations#index'
    post    'reservations/create' => 'reservations#create'
    get    'reservations/all' => 'reservations#all'
    delete    'reservations/destroy' => 'reservations#destroy'
    get    'newauth'     => 'application#newauth'
    get    "/auth/:provider/callback" => 'application#createauth'
    
    resources :users, :maintenance_forms, :reservations

end

app/models/maintenanceForm.rb
class MaintenanceForm < ActiveRecord::Base
	validates :issue_string, presence: true, length: { maximum: 1000 }
	
end

app/controllers/maintenance_controller.rb
class MaintenanceFormsController < ApplicationController
  def new
    @maintenance_form = MaintenanceForm.new
  end

  def index
    @maintenance_form = MaintenanceForm.all
  end

  def show
  @maintenance_form = MaintenanceForm.find(params[:id])
  end

  def create
    @maintenance_form = MaintenanceForm.new(params[:issue_string])
    if @maintenance_form.save
      flash[:success] = "Thank you for letting us know, we will address the issue."
      redirect_to @maintenance_form
    else
      render 'new_request'
    end

  end

  #private

    #def maintenance_params
      #params.require(:maintenance_form).permit(:issueString)
    #end

end

app/helpers/maintenance_helper.rb
module MaintenanceHelper
end

app/views/maintenance/_form.html.erb
<%= form_for(@maintenance_form) do |f| %>
  <% if @maintenance_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maintenance_form.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @maintenance_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :issue_string %><br>
    <%= f.text_field :issue_string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maintenance/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Maintenance Requests</h1>

<table>
  <thead>
    <tr>
      <th>Problem</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maintenance_form.each do |maintenanceF| %>
      <tr>
		<td><%= maintenanceF.id %></td>
        <td><%= maintenanceF.issue_string %></td>
        <td><%= maintenanceF.created_at %></td>
		    <td><%= maintenanceF.fixed %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/maintenance/new.html.erb
<h1>New Maintenance Request</h1>

<%= render 'form' %>

<%= link_to 'Back', maintenance_forms_path %>

app/views/maintenance/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Problem:</strong>
  <%= @maintenance.issueString %>
</p>

<p>
  <strong>Date/Time:</strong>
  <%= @maintenance.created_at %>
</p>

<%= link_to 'Back', maintenance_path %>